opensandiego/sdvv-frontend

README.md
Updated README.md link so that it goes to the correct contributing guide
=> updated README.md link, line 35 

src/app/components/candidate-card/candidate-card.component.scss, src/app/components/home/home.component.html, src/app/components/home/home.component.scss, src/app/components/mayor/mayor.component.scss
Added a footer to the home component, adjusted the spacing on the home page slightly, and condensed some of the button scss
=> Added footer and some minor styling tweaks

README.md, src/app/app.module.ts, src/app/components/home/home.component.html, src/app/components/home/home.component.scss, src/app/components/mayor/mayor.component.ts
I started work on the sidenav and added the styling for active links. Submenus still need to be added/updated.
=> restyled sidenav based on new mocks, first pass

src/app/app-routing.module.ts, src/app/app.component.html, src/app/components/home/home.component.html, src/app/components/home/home.component.scss, src/app/components/splash/splash.component.html, src/app/components/splash/splash.component.scss, src/app/styles/_elements.scss
I updated the splash page html/css. I tried updating the routing too but you might have to double check my work to make sure it is right. The buttons don't currently work correctly. I may need some help fixing that.
=> Updated splash page

src/app/components/home/home.component.html, src/app/components/home/home.component.scss, src/app/components/home/home.component.ts
=> Fixed sidenav

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/components/faq/faq.component.html, src/app/components/faq/faq.component.scss, src/app/components/faq/faq.component.spec.ts, src/app/components/faq/faq.component.ts, src/app/components/home/home.component.html, src/app/components/home/home.component.scss, src/app/components/index.ts, src/app/components/splash/splash.component.html, src/app/components/splash/splash.component.scss, src/app/components/under-construction/under-construction.component.html, src/app/styles/_global.scss
Optimized the splash page for mobile
=> Optimize splash page for mobile

src/assets/candidates/2020/mayor/barbara_bry/barbara_bry.json, src/assets/candidates/2020/mayor/daniel_j._smiechowski/daniel_j._smiechowski.json, src/assets/candidates/2020/mayor/rich_riel/rich_riel.json, src/assets/candidates/2020/mayor/richard_m._hansen/richard_m._hansen.json, src/assets/candidates/2020/mayor/tasha_williamson/tasha_williamson.json, src/assets/candidates/2020/mayor/todd_gloria/todd_gloria.json, src/assets/candidates/2020/other/cedric_s._green/cedric_s._green.json, src/assets/candidates/2020/other/gita_pllelbaum_singh/gita_pllelbaum_singh.json, src/assets/candidates/2020/other/jarvis_e._gandy/jarvis_e._gandy.json, src/scripts/calculation_download_gdrive_info.py
This field indicates whether the candidate is in the general election. It's updated from the "In General" field in the source google sheet. This contains the updated script and JSON files.
=> Added "in general" field to the candidate json files.

src/scripts/shared_calculations.py
=> Added netfile_api_2018.csv to the csv files being used for calculating the values in the candidate JSON files

src/app/components/candidate-card/candidate-card.component.scss, src/app/components/home/home.component.html, src/app/components/home/home.component.scss
Added a three bar icon (hamburger) to show/hide the
=> Menu Toggle on Mobile

src/app/components/candidate-card-expanded/candidate-card-expanded.component.html, src/app/components/home/home.component.ts
This patch should resolve the build error seen when running **ng build --prod**.
=> update files to avoid build error

src/app/components/candidate-card-expanded/candidate-card-expanded.component.ts
Aside from resolving the issue mentioned, I noticed the numbers weren't updating. I think this is the way to fix that. I'm new to Angular, so please check!
=> Fix https://github.com/opensandiego/sdvv-frontend/issues/104 and make numbers actually update

src/scripts/driver_script.js
Driver script changed to test several python commands to find one that runs python 3. Also changed to download CSV files from Firebase Storage before running JSON update scripts. 
This should fix #117 
@BolunThompson Please test this.
=> Python3 fix for driver script

src/app/components/candidate-card-expanded/candidate-card-expanded.component.html
=> Updated link to point to candidate website

src/app/components/candidate-card-expanded/candidate-card-expanded.component.html, src/app/components/candidate-card-expanded/candidate-card-expanded.component.scss, src/assets/candidates/2020/city_attorney/cory_briggs/cory_briggs.json, src/assets/candidates/2020/city_attorney/marra_w._elliot/marra_w._elliot.json, src/assets/candidates/2020/city_council_district_1/aaron_brennan/aaron_brennan.json, src/assets/candidates/2020/city_council_district_1/harid_puentes/harid_puentes.json, src/assets/candidates/2020/city_council_district_1/joe_lacava/joe_lacava.json, src/assets/candidates/2020/city_council_district_1/sam_nejabat/sam_nejabat.json, src/assets/candidates/2020/city_council_district_1/will_moore/will_moore.json, src/assets/candidates/2020/city_council_district_3/adrian_kwiatkowski/adrian_kwiatkowski.json, src/assets/candidates/2020/city_council_district_3/chris_olsen/chris_olsen.json, src/assets/candidates/2020/city_council_district_3/stephen_whitburn/stephen_whitburn.json, src/assets/candidates/2020/city_council_district_3/toni_duran/toni_duran.json, src/assets/candidates/2020/city_council_district_5/issac_wang/issac_wang.json, src/assets/candidates/2020/city_council_district_5/joe_leventhal/joe_leventhal.json, src/assets/candidates/2020/city_council_district_7/monty_mcintyre/monty_mcintyre.json, src/assets/candidates/2020/city_council_district_7/noli_zosa/noli_zosa.json, src/assets/candidates/2020/city_council_district_7/raul_campillo/raul_campillo.json, src/assets/candidates/2020/city_council_district_7/wendy_wheatcroft/wendy_wheatcroft.json, src/assets/candidates/2020/city_council_district_9/andrew_gade/andrew_gade.json, src/assets/candidates/2020/city_council_district_9/johnny_lee_dang/johnny_lee_dang.json, src/assets/candidates/2020/city_council_district_9/kelvin_h._barrios/kelvin_h._barrios.json, src/assets/candidates/2020/city_council_district_9/ross_naismith/ross_naismith.json, src/assets/candidates/2020/city_council_district_9/sam_bedwell/sam_bedwell.json, src/assets/candidates/2020/city_council_district_9/sean_elo/sean_elo.json, src/assets/candidates/2020/mayor/barbara_bry/barbara_bry.json, src/assets/candidates/2020/mayor/scott_sherman/scott_sherman.json, src/assets/candidates/2020/mayor/tasha_williamson/tasha_williamson.json, src/assets/candidates/2020/mayor/todd_gloria/todd_gloria.json, src/scripts/driver_script.js
Robert created update to script so that when python scripts are run it detects if python3 is installed as this is a requirement for the program. Tested and confirmed updates are working properly.
Additionally, updated candidate json files
=> Updating python3 requirements for dev to master when running driver_script.js

package.json, src/scripts/driver_script.js
This updates the driver script to be able to run from outside of the directory that it is in. This also adds an npm script that runs driver script.
**Use:** npm run update-data
=> Update driver script

package.json
Updated the script command **npm run build** to include the --prod flag.
=> added prod to ng build command

src/scripts/candidate_calculation_in_vs_out.js, src/scripts/driver_script.js, src/scripts/shared_routines.js
This now updates both sets of the city council json files.
=> update json files in both city council paths

src/app/components/candidate-card-expanded/candidate-card-expanded.component.html, src/app/components/candidate-card-expanded/candidate-card-expanded.component.scss, src/app/components/candidate-card-expanded/candidate-card-expanded.component.ts, src/app/components/faq/faq.component.html
=> Tooltips and FAQ Rewording

.github/workflows/get_transactions_from_netfile.yml, package.json, src/assets/candidates/2020/campaign_race_totals.json, src/assets/candidates/2020/city_council/district_3/toni_duran/toni_duran.json, src/assets/candidates/2020/city_council/district_7/noli_zosa/noli_zosa.json, src/assets/candidates/2020/city_council/district_7/raul_campillo/raul_campillo.json, src/assets/candidates/2020/city_council_district_3/toni_duran/toni_duran.json, src/assets/candidates/2020/city_council_district_7/noli_zosa/noli_zosa.json, src/assets/candidates/2020/city_council_district_7/raul_campillo/raul_campillo.json, src/assets/candidates/2020/mayor/barbara_bry/barbara_bry.json, src/assets/candidates/2020/mayor/todd_gloria/todd_gloria.json, src/scripts/download_transactions_to_csv.js
This also includes minor fixes to get_transactions_from_netfile.yml , package.json, and download_transactions_to_csv.js.
=> Update json files and csv transaction data as of 10/13/2020 

src/app/components/candidate-card-expanded/candidate-card-expanded.component.html
https://github.com/opensandiego/sdvv-frontend/issues/143
=> Issue 143 donut overlap

src/scripts/download_csv_from_firebase.js, src/scripts/driver_script.js, src/scripts/shared_routines.js
This combines the arrays to run the Python and Node commands into a single array named scripts.
This moves the downloading of the CSV files from Firebase Storage into a separate file and includes a call to the file in the scripts array. 
The improves error handling of the called scripts. This will now exit with a code 1 if an error in a called script is found and if Python 3 is not found.
=> Improve driver script 

src/app/app.module.ts, src/app/pipes/round-currency-display.pipe.spec.ts, src/app/pipes/round-currency-display.pipe.ts
This is the extracted pipe additions from PR 208 by @matthew9510
This pipe can be used to implement a number standard from #196
=> Adds pipe roundCurrencyDisplay from PR 208

src/app/components/home/home.component.html, src/app/components/home/home.component.ts, src/app/services/candidate.service.ts
Adds last updated date to home component by pulling from json file.
Closes #160
=> Issue 160 pull last updated date into home component

src/app/components/splash/splash.component.html, src/app/components/splash/splash.component.ts, src/app/services/candidate.service.ts
Shows total number of candidates running for each office in splash component. Reads counts from json file.
Closes #163
=> Issue 163, shows number of candidates in splash component

src/assets/candidates/2020/campaign_candidate_totals.json, src/assets/candidates/2020/campaign_race_totals.json, src/assets/candidates/2020/candidates.json, src/assets/candidates/2020/city_attorney/cory_briggs/cory_briggs.json, src/assets/candidates/2020/city_council/district_1/will_moore/will_moore.json, src/assets/candidates/2020/city_council/district_3/stephen_whitburn/stephen_whitburn.json, src/assets/candidates/2020/city_council/district_9/sean_elo/sean_elo.json, src/assets/candidates/2020/city_council_district_1/will_moore/will_moore.json, src/assets/candidates/2020/city_council_district_3/stephen_whitburn/stephen_whitburn.json, src/assets/candidates/2020/city_council_district_9/sean_elo/sean_elo.json, src/assets/candidates/2020/mayor/barbara_bry/barbara_bry.json
Transaction data up to date as of 2020-12-22.
=> transaction data updated on 2020-12-22

src/app/app.component.spec.ts, src/app/components/candidate-card-expanded/candidate-card-expanded.component.spec.ts, src/app/components/candidate-card/candidate-card.component.spec.ts, src/app/components/city-attorney/city-attorney.component.spec.ts, src/app/components/home/home.component.spec.ts, src/app/components/mayor/mayor.component.spec.ts, src/app/components/splash/splash.component.spec.ts, src/app/services/candidate.service.spec.ts
=> Resolves Issue 232 with testing 

src/app/components/candidate-card-expanded/candidate-card-expanded.component.ts
=> doughnutChart transitions between candidates fix

src/assets/candidates/mock-candidateAssetPaths.ts, src/assets/candidates/mock-candidateNavigationItems.ts
Adds missing candidates to data files.
=> updated candidate data used by services

src/app/components/candidate-card-expanded/candidate-card-expanded.component.html, src/app/components/candidate-card-expanded/candidate-card-expanded.component.ts, src/app/services/candidate-data.service.ts, src/app/vv-charts/interfaces/raisedVsSpent.ts
Added an interface to model the raised vs spent data.
Added a function to candidate-data service to provide the raised vs spent data.
Updated candidate-card-expanded component to use the above function and provide the results to the raised vs spent component.
=> changed inputs to the raised vs spent component to use output from the candidate-data service

src/app/components/candidate-card-expanded/candidate-card-expanded.component.html, src/app/components/candidate-card-expanded/candidate-card-expanded.component.ts, src/app/vv-charts/donations-by-group/donations-by-group.component.ts
Updated candidate-card-expanded component to use the data from candidate-data service and provide the results to the donations-by-group component.
Revised input to donations-by-group component to use the simplified data structure from candidate-data service.
=> changed inputs to the donations by group component to use output from the candidate-data service

src/app/app.module.ts, src/app/components/candidate-details-header/candidate-details-header.component.html, src/app/components/candidate-details-header/candidate-details-header.component.scss, src/app/components/candidate-details-header/candidate-details-header.component.stories.ts, src/app/components/candidate-details-header/candidate-details-header.component.ts
Adds **candidate details header component** for use in a future **candidate details component**.
Based on [UI Design Prototype](https://xd.adobe.com/view/2515850f-37db-4f50-5de2-93d5cec8d021-5324/) pages 20, 24, and 25
**Layout at 300px**
**Layout at 350px**
**Layout at 400px**
**Layout at 550px**
**Layout at 800px**
**Layout at 1500px**
=> Adds candidate details header component

src/app/vv-charts/raised-by-location-bar/raised-by-location-bar.component.html, src/app/vv-charts/raised-by-location-bar/raised-by-location-bar.component.scss, src/app/vv-charts/raised-by-location-bar/raised-by-location-bar.component.stories.ts, src/app/vv-charts/raised-by-location-bar/raised-by-location-bar.component.ts, src/app/vv-charts/vv-charts.module.ts
=> adds raised-by-location-bar chart component

src/app/vv-charts/raised-by-outside-money-bar/raised-by-outside-money-bar.component.html, src/app/vv-charts/raised-by-outside-money-bar/raised-by-outside-money-bar.component.scss, src/app/vv-charts/raised-by-outside-money-bar/raised-by-outside-money-bar.component.stories.ts, src/app/vv-charts/raised-by-outside-money-bar/raised-by-outside-money-bar.component.ts, src/app/vv-charts/vv-charts.module.ts
=> adds raised-by-outside-money-bar chart component for full details page

src/app/app.module.ts, src/app/candidate-quick-view/candidate-quick-view.module.ts
Will be used for the components related to the candidate Details/QuickView.
=> added Candidate QuickView module

src/app/vv-charts/total-raised-bar/total-raised-bar.component.html, src/app/vv-charts/total-raised-bar/total-raised-bar.component.scss, src/app/vv-charts/total-raised-bar/total-raised-bar.component.stories.ts, src/app/vv-charts/total-raised-bar/total-raised-bar.component.ts, src/app/vv-charts/vv-charts.module.ts
Medium width with bar tooltip
Narrow width
=> added total-raised-bar component

src/app/candidate-quick-view/candidate-quick-view.module.ts, src/app/candidate-quick-view/expanded-average-donation/expanded-average-donation.component.html, src/app/candidate-quick-view/expanded-average-donation/expanded-average-donation.component.scss, src/app/candidate-quick-view/expanded-average-donation/expanded-average-donation.component.stories.ts, src/app/candidate-quick-view/expanded-average-donation/expanded-average-donation.component.ts, src/app/candidate-quick-view/expanded-raised-vs-spent/expanded-raised-vs-spent.component.html, src/app/candidate-quick-view/expanded-raised-vs-spent/expanded-raised-vs-spent.component.scss, src/app/candidate-quick-view/expanded-raised-vs-spent/expanded-raised-vs-spent.component.stories.ts, src/app/candidate-quick-view/expanded-raised-vs-spent/expanded-raised-vs-spent.component.ts, src/app/vv-charts/raised-vs-spent-bar/raised-vs-spent-bar.component.html, src/app/vv-charts/raised-vs-spent-bar/raised-vs-spent-bar.component.scss, src/app/vv-charts/raised-vs-spent-bar/raised-vs-spent-bar.component.stories.ts, src/app/vv-charts/raised-vs-spent-bar/raised-vs-spent-bar.component.ts, src/app/vv-charts/raised-vs-spent/raised-vs-spent.component.stories.ts, src/app/vv-charts/vv-charts.module.ts
- updated existing raised-vs-spent component to show in Storybook
- added expanded-average-donation component to candidate-quick-view.module
- added new raised-vs-spent-bar component to vv-charts.module which uses ECharts
- added expanded-raised-vs-spent.component  to candidate-quick-view.module
=> Raised vs spent update

src/app/candidate-quick-view/candidate-quick-view.module.ts, src/app/candidate-quick-view/expanded-raised-in-vs-out/expanded-raised-in-vs-out.component.html, src/app/candidate-quick-view/expanded-raised-in-vs-out/expanded-raised-in-vs-out.component.scss, src/app/candidate-quick-view/expanded-raised-vs-spent/expanded-raised-vs-spent.component.scss, src/app/components/candidate-card/candidate-card.component.html, src/app/components/candidate-card/candidate-card.component.scss, src/app/vv-charts/raised-vs-spent-bar/raised-vs-spent-bar.component.scss
Updates mostly to the CSS of some of the chart container components. These are needed to allow components to show properly when placed into the quick view / expanded view and within flexboxes.
=> chart container / quick view components css updates

src/app/candidate-details/candidate-details-header/candidate-details-header.component.html, src/app/candidate-details/candidate-details-header/candidate-details-header.component.stories.ts, src/app/candidate-details/candidate-details-header/candidate-details-header.component.ts, src/app/candidate-details/candidate-details.module.ts, src/app/candidate-details/details-total-raised/details-total-raised.component.html, src/app/candidate-details/details-total-raised/details-total-raised.component.scss, src/app/candidate-details/details-total-raised/details-total-raised.component.stories.ts, src/app/candidate-details/details-total-raised/details-total-raised.component.ts, src/app/candidate-details/details-total-spent/details-total-spent.component.html, src/app/candidate-details/details-total-spent/details-total-spent.component.scss, src/app/candidate-details/details-total-spent/details-total-spent.component.stories.ts, src/app/candidate-details/details-total-spent/details-total-spent.component.ts, src/app/candidate-details/top-categories-table/top-categories-table.component.html, src/app/candidate-details/top-categories-table/top-categories-table.component.scss, src/app/candidate-details/top-categories-table/top-categories-table.component.stories.ts, src/app/candidate-details/top-categories-table/top-categories-table.component.ts, src/app/candidate-quick-view/expanded-quick-view/expanded-quick-view.component.stories.ts, src/app/vv-charts/total-spent-donut/total-spent-donut.component.html, src/app/vv-charts/total-spent-donut/total-spent-donut.component.scss, src/app/vv-charts/total-spent-donut/total-spent-donut.component.stories.ts, src/app/vv-charts/total-spent-donut/total-spent-donut.component.ts
Added components for the details view. These are container components that contain a chart or table component.
Details total raised component
Details total spent component wide view
Details total spent component narrow view
=> New components created for the details view

src/app/candidate-details/candidate-details.module.ts, src/app/candidate-details/details-raised-spent-summary/details-raised-spent-summary.component.html, src/app/candidate-details/details-raised-spent-summary/details-raised-spent-summary.component.scss, src/app/candidate-details/details-raised-spent-summary/details-raised-spent-summary.component.stories.ts, src/app/candidate-details/details-raised-spent-summary/details-raised-spent-summary.component.ts
this will be used in the raised-spent tab
=> added details-raised-spent-summary

src/app/candidate-details/details-raised-by-industry/details-raised-by-industry.component.html, src/app/candidate-details/details-raised-by-industry/details-raised-by-industry.component.stories.ts, src/app/candidate-details/details-raised-by-industry/details-raised-by-industry.component.ts, src/app/candidate-details/details-tab-title/details-tab-title.component.html, src/app/candidate-details/details-tab-title/details-tab-title.component.scss, src/app/candidate-details/details-tab-title/details-tab-title.component.stories.ts, src/app/candidate-details/details-tab-title/details-tab-title.component.ts
=> Details tab title

src/app/candidate-details/details-raised-by-industry/details-raised-by-industry.component.html, src/app/candidate-details/details-raised-by-industry/details-raised-by-industry.component.scss, src/app/candidate-details/details-raised-by-industry/details-raised-by-industry.component.ts, src/app/candidate-details/details-tab-raised-by-industry/details-tab-raised-by-industry.component.html, src/app/candidate-details/details-tab-raised-by-industry/details-tab-raised-by-industry.component.scss, src/app/candidate-details/details-tab-raised-by-industry/details-tab-raised-by-industry.component.stories.ts, src/app/candidate-details/details-tab-raised-by-industry/details-tab-raised-by-industry.component.ts, src/app/candidate-details/details-tab-raised-v-spent/details-tab-raised-v-spent.component.stories.ts, src/app/candidate-details/details-tab-title/details-tab-title.component.stories.ts, src/app/vv-charts/raised-by-industry-bar/raised-by-industry-bar.component.html, src/app/vv-charts/raised-by-industry-bar/raised-by-industry-bar.component.scss, src/app/vv-charts/raised-by-industry-bar/raised-by-industry-bar.component.ts
=> Details tab raised by industry

src/app/candidate-details/details-tab-raised-by-location/details-tab-raised-by-location.component.html, src/app/candidate-details/details-tab-raised-by-location/details-tab-raised-by-location.component.scss, src/app/candidate-details/details-tab-raised-by-location/details-tab-raised-by-location.component.stories.ts, src/app/candidate-details/details-tab-raised-by-location/details-tab-raised-by-location.component.ts
=> added details-tab-raised-by-location component

angular.json, package.json, src/app/campaign-disclosure-explorer/election-candidate-updater/election-candidate-updater.component.html, src/app/campaign-disclosure-explorer/election-candidate-updater/election-candidate-updater.component.ts, src/app/campaign-disclosure-explorer/election-data-updater/election-data-updater.component.ts, src/styles.scss
=> Explorer updates

src/app/campaign-disclosure-explorer/campaign-data-changes.service.ts, src/app/campaign-disclosure-explorer/election-candidate-updater/election-candidate-updater.component.html, src/app/campaign-disclosure-explorer/election-candidate-updater/election-candidate-updater.component.ts, src/app/campaign-disclosure-explorer/election-data-updater/election-data-updater.component.html, src/app/campaign-disclosure-explorer/election-data-updater/election-data-updater.component.ts
and ElectionDataUpdater Component
=> improvements in ElectionCandidateUpdater Component

src/app/navigation-menu/components/side-menu/side-menu.component.scss, src/app/navigation-menu/components/side-menu/side-menu.component.ts, src/app/vv-charts/outside-money-stacked-bar/outside-money-stacked-bar.component.ts
=> Menu expands to show selected candidate, fix to Outside Money chart

src/app/candidate-details/candidate-details-header/candidate-details-header.component.stories.ts, src/app/candidate-details/details/details.component.stories.ts, src/app/candidate-quick-view/expanded-quick-view/expanded-quick-view.component.stories.mock-candidate.service.ts, src/app/candidate-quick-view/expanded-quick-view/expanded-quick-view.component.stories.ts, src/app/candidate/candidate-card/candidate-card.component.stories.mock-candidate.service.ts, src/app/candidate/candidate-card/candidate-card.component.stories.ts
Several of the storybook files for components were broken after the components were revised. This fixes some of them.
Fix for CandidateCardComponent storybook file.
Fix for ExpandedQuickViewComponent storybook file.
Fix for CandidateDetailsHeaderComponent storybook file.
=> Fixes to storybook files

cypress/integration/sdvv-frontend_spec.js, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/navigation-menu/components/header/header.component.html, src/app/navigation-menu/components/header/header.component.ts, src/app/public/components/breadcrumb/breadcrumb.component.ts, src/app/public/public-routing.module.ts
Removed OfficeModule from AppRoutingModule.
Changed path of SplashComponent to /home
Added redirect from root path '' to the 2022 election year '/year/2022'.
=> Set a default year on root URL

package-lock.json, package.json
Updates angular-fontawesome to 0.10.1
Updates angular-in-memory-web-api to 0.13.0
Updates echarts from 5.1.1 to 5.2.2
=> Update packages fontawesome and angular-in-memory-web-api

projects/lib-ui-components/src/lib/candidate-card/candidate-card.component.html, projects/lib-ui-components/src/lib/candidate-card/candidate-card.component.scss, projects/lib-ui-components/src/lib/candidate-card/candidate-card.component.stories.ts, projects/lib-ui-components/src/lib/candidate-card/candidate-card.component.ts, projects/lib-ui-components/src/lib/candidate-card/candidate-card.module.ts, projects/lib-ui-components/src/lib/lib-ui-components.models.ts, projects/lib-ui-components/src/public-api.ts
Use of global styles for colors in candidate card component needs to be changed to use a theme.
=> Lib component candidate card

.github/workflows/deploy_to_dev.yml, .github/workflows/deploy_to_prod.yml
Updates to fix broken GitHub Actions deployment.
=> Updates GitHub actions for deployment
