opensandiego/sdvv-frontend

- src/scripts/candidate_calculation_amount_raised.py
- src/scripts/candidate_calculation_amount_spent.py
- src/scripts/candidate_calculation_industry.py
- src/scripts/shared_calculations.py
This rounds the values in the fields which are currently float numbers in the candidate JSON files to the nearest whole number.
This does not convert the new value to a string, see PR #69 for that.
The percentage that each industry donated to each candidate isn't currently rounded, should that be converted to an int and rounded? E.g, from 0.2468 to 25% (or 24.7%).
> Round the float fields dealing with money to the nearest whole number in the candidate JSON files

- src/scripts/candidate_calculation_industry.py
- src/scripts/shared_calculations.py
Previously, numbers were being written as integers in the JSON files. This changes them to be written as strings.
This also includes some minor refactoring.
> Make candidate calculation scripts enter numbers as strings into the candidate JSON files

- src/scripts/candidate_calculation_industry.py
Previously, the percentage that an industry donated to a candidate in the candidate JSON files were a decimal percentage (e.g 0.24721). This changes it so that they're rounded integer percentages (e.g 25).
> Have the percentage that each industry donated to a candidate be a whole number

- src/app/components/candidate-card-expanded/candidate-card-expanded.component.html
- src/app/components/candidate-card-expanded/candidate-card-expanded.component.scss
For the amount column on the candidate expansion card this right justifies the number and eliminates the decimals.
This addresses item 3 in issue #102.
> Industry table amount fix on candidate expansion card

- src/app/components/candidate-card-expanded/candidate-card-expanded.component.html
- src/app/components/candidate-card-expanded/candidate-card-expanded.component.scss
For the percent column on the candidate expansion card this right justifies the number and removed two trailing zeros from the percentage. These percentages appear to be computed by dividing the industry amount by the total raised.
This addresses the formating relating to item 4 on issue #102. This does not address the computation of the percentage.
> Industry table percentage display fix on candidate expansion card

- src/app/components/candidate-card-expanded/candidate-card-expanded.component.html
- src/app/components/candidate-card-expanded/candidate-card-expanded.component.scss
The header row on the industry table was there but not showing. It now shows up.
Fixes Item 1 on #102
> updated to show header row on industry table

- package-lock.json
This fixes some of the vulnerabilities shown when running npm install.  The remaining vulnerabilities involve a potentially breaking changes. The summarized results of npm audit are shown below. Three involve updating to Angular 10. The other two karma and protractor might be used for browser testing. 
```
SEMVER WARNING: Recommended action is a potentially breaking change
SEMVER WARNING: Recommended action is a potentially breaking change
SEMVER WARNING: Recommended action is a potentially breaking change
SEMVER WARNING: Recommended action is a potentially breaking change
```
> updated package-lock.json by running npm audit fix

- src/scripts/calculation_download_gdrive_info.py
This changes it so that when the "District" field on the source google sheet is not 0 or empty, a folder "district_{num}" is generated to put the candidate JSON files for the district in. This currently only happens in city council races. E.G instead of directory "city_council/candidate_name" it would be "city_council/district_num/candidate_name".
> Generate "district_{num}" folders in city council races

- src/assets/candidates/2020/candidates.json
This changes the location that the json files are read from for the city council candidates.
New folder path example:
`assets/candidates/2020/city_council/district_1/joe_lacava/joe_lacava.json`
Old folder path example:
`assets/candidates/2020/city_council_district_1/joe_lacava/joe_lacava.json`
> Changed folder path for city council candidates

- src/scripts/driver_script.js
Add a flag to driver_script.js to support skipping the download of the csv files from Firebase Stored. This is needed to run in a Github action where the csv files are downloaded from the Github API.
```
Usage: driver_script.js [--skip-download boolean]
Options:
--help                 Show help                                     [boolean]
--sk, --skip-download  Do not download csv files.                    [boolean]
Examples:
driver_script.js --skip-download
driver_script.js --sk
driver_script.js --sk=true
```
> added skip-download flag to driver_script.js

- src/scripts/candidate_calculation_in_vs_out.js
The FilerName field from the CSV files is compared to Committee Name (Filer_Name) in the Google Sheet to determine matching
committees. This change does the comparison using the same case so that committee names with non matching case are not missed. This fix is for the in vs out calculation.
> Fix to compare Filer/Committee names in same case for in vs out calculation

- src/scripts/candidate_calculation_in_vs_out.js
- src/scripts/candidate_calculation_in_vs_out_district.js
- src/scripts/candidate_calculation_in_vs_out_shared.js
- src/scripts/driver_script.js
Revises City Council calculations to use a set of zip codes and district values to indicate the zip codes in each district. The City Council calculations are done in a separate script file and a call to it is added to driver_script.js. Functions used in new and existing **in vs out** calculations are moved to a new script file. 
Fixes #168
> Update in vs out to use district zip codes

- src/scripts/average_donation_calculation.py
There are two source columns in the source CSV files for how much was contributed to a candidate, Tran_Amt1 and Tran_Amt2. This switches it so that in "average_donation_calculation.py" Tran_Amt1 is used instead of Tran_Amt2. This makes it consistent with the other calculation scripts.
> Switch source contribution data column for "average_donation_calculation.py" to Tran_Amt1

- src/scripts/shared_calculations.py
Currently, the names of the committees are compared case sensitively. This causes issues where a committee name is entered with a different case in different places. This changes it so that the comparisons between committee names are case insensitive.
> Case insensitive committee name comparisons

- src/scripts/calculation_download_gdrive_info.py
This changes it so that default data is generated when the candidate JSON files are created.
> Have default data be generated for the candidate JSON files

- src/app/components/home/home.component.html
now homecomponent.html has no reference to city council. the head of a deep tree does not have a router link to render a different component. eg:- when we click on mayor , mayor component is called , whereas when we click on city council, there is no component called city council which is called.
> removed cityCouncil conditional statement from home.component.html. 

- firebase.json
This should resolve the issue where a reloaded page hosted in Firebase gets a 'Page Not Found' error.
> Updated firebase.json so all requests go through /index.html

- src/assets/candidates/2020/candidates.json
This fixes an issue with the district names not showing in the side menu. This issue was introduced in PR #215.
> Restored names in candidates.json

- src/scripts/calculation_download_gdrive_info.py
- src/scripts/number_of_candidates_calculation.py
- src/scripts/shared_calculations.py
This is a script that calculates how many candidates are in each race by year and outputs them to `/src/assets/candidates/{year}/campaign_candidate_totals.json`.
Closes #162.
> Script to calculate how many candidates are in each race

- src/scripts/driver_script.js
Previously, the script "number_of_candidates_calculation.py" wasn't run when the driver script ("src/scripts/driver_script.js") was run. This changes it so that it is run.
> Change the driver script to run the "number_of_candidates_calculation.py" script

- src/app/components/splash/splash.component.html
- src/app/components/splash/splash.component.ts
- src/app/pipes/round-currency-display.pipe.ts
- src/app/services/candidate.service.ts
Adds candidate sums to splash page
The formating pipe from PR 222 should be used for the totals in the splash component after both it and this have been merged. This displays the amounts without rounding. For example for City Attorney the Total Raised shows as $639706.
Closes #159
> Issue 159, Read mayor, city council and city attorney sums from JSON file

- documentation.json
- src/app/vv-charts/raised-in-out-donut/raised-in-out-donut.component.html
- src/app/vv-charts/raised-in-out-donut/raised-in-out-donut.component.scss
- src/app/vv-charts/raised-in-out-donut/raised-in-out-donut.component.stories.ts
- src/app/vv-charts/raised-in-out-donut/raised-in-out-donut.component.ts
- src/app/vv-charts/round-currency.pipe.ts
Added a standalone component for the inside vs. outside spending doughnut chart. This includes a .component.stories.ts file to be used with Storybook to test the component. The .component.stories.ts file includes some basic instructions on how to use a copy of the file for working on other components.
This component still needs some work on adapting the .scss file to match the existing style from the integrated chart in candidate-card-expanded.component. Also, the title needs to be centered and the size needs to be more adaptive to its context.
Closes #142
> Inside vs. Outside money standalone component

- documentation.json
- src/app/vv-charts/outside-money-bar/outside-money-bar.component.html
- src/app/vv-charts/outside-money-bar/outside-money-bar.component.scss
- src/app/vv-charts/outside-money-bar/outside-money-bar.component.stories.ts
- src/app/vv-charts/outside-money-bar/outside-money-bar.component.ts
- src/app/vv-charts/round-currency.pipe.ts
Added a standalone component for the outside spending horizontal bar chart. This includes a .component.stories.ts file to be used with Storybook to test the component.
This component still needs some work on adapting the .scss file to match the existing style from the integrated chart in candidate-card-expanded.component. Also, the title needs to be centered.
> Outside money standalone component

- src/app/vv-charts/raised-in-out-donut/raised-in-out-donut.component.html
- src/app/vv-charts/raised-in-out-donut/raised-in-out-donut.component.ts
- src/app/vv-charts/vv-charts.module.ts
**outside-money-bar** and **raised-in-out-donut** components are now included in vv-charts module file.
> resolved issue with including components in module

- src/app/app.module.ts
- src/app/components/candidate-navigation/candidate-navigation.component.html
- src/app/components/candidate-navigation/candidate-navigation.component.ts
Adds candidate navigation component for the sidenav menu. This uses the candidate-data.service rather than accepting the candidate data as input.
Know issues: This component does not use its own CSS/SCSS but depends on the styles set in the parent Home component.
Component is not currently active in the site. When it is it used it will replace the contents inside of the <mat-drawer> element in the Home component template. The routing may need to be updated when this component is added to the Home component template.
Closes #252
> candidate navigation component

- src/app/candidate-quick-view/candidate-quick-view.module.ts
- src/app/candidate-quick-view/expanded-chart-title/expanded-chart-title.component.html
- src/app/candidate-quick-view/expanded-chart-title/expanded-chart-title.component.scss
- src/app/candidate-quick-view/expanded-chart-title/expanded-chart-title.component.stories.ts
- src/app/candidate-quick-view/expanded-chart-title/expanded-chart-title.component.ts
This can be used by the chart component containers in the expanded card.
With tooltip text showing
> added expanded-chart-title component

- src/app/candidate-quick-view/candidate-quick-view.module.ts
- src/app/candidate-quick-view/expanded-outside-money/expanded-outside-money.component.html
- src/app/candidate-quick-view/expanded-outside-money/expanded-outside-money.component.scss
- src/app/candidate-quick-view/expanded-outside-money/expanded-outside-money.component.stories.ts
- src/app/candidate-quick-view/expanded-outside-money/expanded-outside-money.component.ts
Typical width
Medium width
Narrow width
With tooltip text showing
With bar tooltip showing
> added expanded-outside-money component within Candidate QuickView module

- src/app/vv-charts/outside-spending-bar/outside-spending-bar.component.ts
Moved text from left side to be with the amount on the right end of the bar .
> updated outside-spending-bar

- src/app/candidate-details/candidate-details.module.ts
- src/app/candidate-details/details-container-outside-money/details-container-outside-money.component.html
- src/app/candidate-details/details-container-outside-money/details-container-outside-money.component.scss
- src/app/candidate-details/details-container-outside-money/details-container-outside-money.component.stories.ts
- src/app/candidate-details/details-container-outside-money/details-container-outside-money.component.ts
- src/app/candidate-details/details-raised-by-industry/details-raised-by-industry.component.stories.ts
- src/app/candidate-details/details-tab-outside-money/details-tab-outside-money.component.html
- src/app/candidate-details/details-tab-outside-money/details-tab-outside-money.component.scss
- src/app/candidate-details/details-tab-outside-money/details-tab-outside-money.component.stories.ts
- src/app/candidate-details/details-tab-outside-money/details-tab-outside-money.component.ts
- src/app/candidate-details/details-total-raised/details-total-raised.component.stories.ts
- src/app/candidate-details/details-total-spent/details-total-spent.component.stories.ts
- src/app/candidate-details/top-categories-table/top-categories-table.component.html
- src/app/candidate-details/top-categories-table/top-categories-table.component.ts
- src/app/vv-charts/outside-money-stacked-bar/outside-money-stacked-bar.component.html
- src/app/vv-charts/outside-money-stacked-bar/outside-money-stacked-bar.component.scss
- src/app/vv-charts/outside-money-stacked-bar/outside-money-stacked-bar.component.stories.ts
- src/app/vv-charts/outside-money-stacked-bar/outside-money-stacked-bar.component.ts
- src/app/vv-charts/vv-charts.module.ts
The title of the Outside Money tab. has been changed from 'Amount Raised' to 'Independent Expenditures'
The Outside Spending chart container links the highlighting of the chart and the tables together. 
This chart will replace the other Outside Money chart in the detail view. This chart supports highlighting individual bar elements and the max range for each side will now be then same for the opposed and support bars.
> Outside money chart

- src/app/vv-charts/raised-in-vs-out-donut/raised-in-vs-out-donut.component.ts
> Fix for RaisedInVsOutDonut when input is null.

- angular.json
- package.json
- src/environments/environment.db-remote.ts
Developer can work on app without running the database locally.
To do so use the npm script: **start:db:remote**
`npm run start:db:remote`
> Adds npm script to run against a remote database.

- src/app/details-raised-spent/components/details-total-spent/details-total-spent.component.ts
- src/app/vv-charts/total-spent-donut/total-spent-donut.component.ts
closes #373 
Displays **not categorized** for the group of expenditures that have a blank in the **Expn_Code** field.
And
Some of the description texts did not fit well inside the donut.
Below is the before image:
Now shows expense code inside donut instead of the description.
> Fixes issue 373

- src/app/public/pipes/round-currency-display.pipe.ts
- src/app/shared/number-formatter.ts
Fixed number suffix when amount was under a million.
Note the City Council amount in the Before 
Year: 2022
and Year: 2020
Note the City Council amount in the After
Year: 2022
and Year: 2020
> Fixes number rounding with suffixes.

- projects/lib-ui-charts/src/lib/contributions-by-code-stacked-bar/contributions-by-code-stacked-bar.component.stories.ts
- projects/lib-ui-charts/src/lib/contributions-by-code-stacked-bar/contributions-by-code-stacked-bar.component.ts
- projects/lib-ui-charts/src/lib/contributions-by-code-stacked-bar/contributions-by-code-stacked-bar.module.ts
- src/app/graphql/contributions-by-code-gql/contributions-by-code-gql.component.stories.ts
- src/app/graphql/contributions-by-code-gql/contributions-by-code-gql.component.ts
- src/app/graphql/contributions-by-code-gql/contributions-by-code-gql.module.ts
- src/app/graphql/contributions-by-code-gql/contributions-by-code-gql.query.ts
This adds a ContributionsByCodeStackedBarComponent and ContributionsByCodeGQLComponent.
**Chart with sample data:**
**Chart with actual data:**
Barbara Bry 2020 - Election year
Todd Gloria 2020 - Election year
Jennifer Campbell 2022 - Election year
Monica Montgomery Steppe 2022 - Election year
> ContributionsByCodeStackedBarComponent
